// Multi-voice support (meeting item 录音多样化, survey ask "different voices"):
// drop extra takes of a syllable into public/audio/syllables/ named
//   <syl><tone>.<voice>.m4a     e.g.  ma1.b.m4a, ma1.c.m4a
// then run:  node scripts/buildSyllableVariants.mjs
// playSyllable() will pick randomly among the default + variants.
import { readdirSync, writeFileSync } from 'fs'

const DIR = 'public/audio/syllables'
const OUT = 'src/utils/syllableVariants.js'

const variants = {}
for (const f of readdirSync(DIR)) {
  const m = f.match(/^([a-z]+[1-4])\.([a-z0-9]+)\.m4a$/i)
  if (!m) continue
  ;(variants[m[1].toLowerCase()] ||= []).push(f)
}

writeFileSync(OUT, `// AUTO-GENERATED by scripts/buildSyllableVariants.mjs — do not edit.
// Extra voice takes per syllable+tone ("ma1" → ["ma1.b.m4a", …]).
export const SYLLABLE_VARIANTS = ${JSON.stringify(variants, null, 2)}
`)
console.log(`Wrote ${OUT}: ${Object.keys(variants).length} syllables with variants`)
